#settings for NginxService
nginx:
  #list of IP addresses to be denied access
  ip-block-list:
    - "192.168.0.1"
    - "192.168.0.2"
  #Path to nginx.conf file
  config-path: "/usr/local/etc/nginx/nginx.conf"
  #Path to the template. Based on it, conf.path is compiled
  template-path: "nginx-config-template.txt"

#default spring settings
spring:
  datasource:
    url: jdbc:h2:file:~/data/applicationProxyDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
    name: applications_proxy
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true #disabling the H2 console

#server settings
server:
  port: 8081
